name: UnknownMessage
author: O_o_Fadi_o_O
version: 1.0
description: UnknownMessage by O_o_Fadi_o_O
main: me.O_o_Fadi_o_O.UnknownMessage.Start
commands:
   unknownmessage:
     description: Show UnknownMessage Help
   um:
     description: /unknownmessage Alias
   umsg:
     description: /unknownmessage Alias