# Default Config
# OnJoin Plugin Made by O_o_Fadi_o_O
# Got any Suggestions or Errors? http://dev.bukkit.org/bukkit-plugins/on-join/
# You can use ColorCodes! &a, &b, &c, &d, &e, &f, &0, &1, &2, &3, &4, &5, &6, &7, &8, &9, &l, &n, &m, &k, &o
# Use false to Disable and true to Enable.
# Available Variables: %player%

EnableJoinMessage: true
JoinMessage: '&8[&a&lJoin&8]&6&l %player%'
EnableLeaveMessage: true
LeaveMessage: '&8[&c&lQuit&8]&6&l %player%'

EnablePlayerJoinMessage: true
PlayerJoinMessage:
  - '&7Welcome &a%player%&7!'
  - '&7This is the PlayerJoinMessage (&aonJoin Plugin&7)'
  - '&7Add &aMultiple Lines &7in the &aConfig&7!'

