name: Survival
author: O_o_Fadi_o_O
version: 1
description: Survival by O_o_Fadi_o_O
main: me.O_o_Fadi_o_O.Survival.Start
commands:
  servers:
    description: Server Selector!
  vippoints:
    description: VIP Points
  omt:
    description: OMT
  perks:
    description: Cosmetic Perks
depend: [LibsDisguises]