ServerList: 40
Friends: 31
Google: 11
YouTube: 10
PlayersVoted:
- BenYOmin_Mango
- eekhoorn2000
- luigicat090
- rienk222
- Bryan20027
- Koning_paul
- jomancool55
- casidas
- playwarrior
- jasonboy7
- jonabuilder1998
- iefke
- WiseGirl84
- jim5491158
- dionb
- Milanekke
- pure_flame
- AntiFighting
- sharewoods
- Selasie
- Kolkje30
- Teleport1409
- PieHatesYou
- WOUT2004ANIKIN
- O_o_Fadi_o_O
- marioandbowser30
- Dimitiris25
- yar2000
- gwnluca
- DavidZG
- pokedude1
- JetCourdGamer
- xxxSpinnetjexxx
- godda28
- Christy_Fristy
- filliph
- asiLukystar
- CreepyCash
- theflyingsockie
- Zachgamer
- 123pika456
- Saibot900
- Maartiek
- varmando
- eliboycool
- kaidon91702
- Jelmer600
- hayden1010101
- napataara
- danny2oo1
- iAmCrazyRudy
- igiboy2012
- colsith
- jimis_321
- arpi22312
- shadowxxs
- regonize11
- jonas22052000
- Ilovedeadlox
- notepoot
- kenava
- quancarlos
- eryn5556
- y0up0wn3d
- Terrick
- Peewee_Gamer
- firedraak
- pimnl2001
- destructor7854
- daanms
- Bartje_zegt
- Theonewhogotaway
- dashland94
- CR4FT1NG_L1M1T
- Broluigi02
- jasperdejong2001
- anoniemmick
- MarkenFrank1
- TychoBoy09
- Sonnetje123
- asfalthoofd
- cvpv
- CaptainCraftin22
- pandapim2
- gapisabelle
- shortstuff0007
- Mystic_Mark_
- Huspoel
- MasterChiefDen
- XspikeheadX
- SuperSonicSparky
- eddieirwin
- siebevanolmen
VotedForServerList:
- luigicat090
- jomancool55
- jasonboy7
- jonabuilder1998
- iefke
- pure_flame
- AntiFighting
- O_o_Fadi_o_O
- yar2000
- gwnluca
- DavidZG
- pokedude1
- JetCourdGamer
- godda28
- asiLukystar
- 123pika456
- Maartiek
- eliboycool
- kaidon91702
- napataara
- danny2oo1
- iAmCrazyRudy
- colsith
- arpi22312
- eryn5556
- Peewee_Gamer
- pimnl2001
- Bartje_zegt
- Theonewhogotaway
- dashland94
- CR4FT1NG_L1M1T
- Broluigi02
- anoniemmick
- MarkenFrank1
- TychoBoy09
- asfalthoofd
- cvpv
- CaptainCraftin22
- Mystic_Mark_
- eddieirwin
VotedForFriends:
- BenYOmin_Mango
- eekhoorn2000
- rienk222
- Bryan20027
- Koning_paul
- casidas
- WiseGirl84
- jim5491158
- dionb
- Milanekke
- sharewoods
- marioandbowser30
- Dimitiris25
- xxxSpinnetjexxx
- Christy_Fristy
- theflyingsockie
- Jelmer600
- hayden1010101
- igiboy2012
- jimis_321
- shadowxxs
- regonize11
- jonas22052000
- kenava
- y0up0wn3d
- Sonnetje123
- gapisabelle
- shortstuff0007
- Huspoel
- XspikeheadX
- SuperSonicSparky
- siebevanolmen
VotedForGoogle:
- Zachgamer
- Ilovedeadlox
- notepoot
- quancarlos
- Terrick
- firedraak
- destructor7854
- daanms
- jasperdejong2001
- pandapim2
- MasterChiefDen
VotedForYouTube:
- playwarrior
- Selasie
- Kolkje30
- Teleport1409
- PieHatesYou
- WOUT2004ANIKIN
- filliph
- CreepyCash
- Saibot900
- varmando
