name: OrbitMinesEmptyWorldGenerator
author: O_o_Fadi_o_O
load: STARTUP
version: 1
description: OrbitMinesEmptyWorldGenerator by O_o_Fadi_o_O
main: me.O_o_Fadi_o_O.OrbitMinesEmptyWorldGenerator.Start
commands:
depend: [Multiverse-Core]