KitPvP: 5
Prison: 4
Creative: 1
SkyBlock: 4
MiniGames: 5
VIPPerks: 5
PlayersVoted:
- BenYOmin_Mango
- WiseGirl84
- T_BUILD
- Teleport1409
- WOUT2004ANIKIN
- Koning_paul
- eekhoorn2000
- iefke
- jasonboy7
- sharewoods
- jonabuilder1998
- jomancool55
- daanms
- Bryan20027
- Milanekke
- playwarrior
- kenava
- casidas
- jim5491158
- XspikeheadX
- jigglegale
- rienk222
- GoldenHeart176
- godda28
- Maartiek
VotedForKitPvP:
- T_BUILD
- Teleport1409
- Milanekke
- rienk222
- godda28
VotedForPrison:
- BenYOmin_Mango
- WOUT2004ANIKIN
- casidas
- XspikeheadX
- GoldenHeart176
VotedForCreative:
- Maartiek
VotedForSkyBlock:
- WiseGirl84
- iefke
- daanms
- jigglegale
VotedForMiniGames:
- eekhoorn2000
- sharewoods
- Bryan20027
- kenava
- jim5491158
VotedForVIPPerks:
- Koning_paul
- jasonboy7
- jonabuilder1998
- jomancool55
- playwarrior
