# Default Config
# CustomBroadcast Plugin Made by O_o_Fadi_o_O
# Got any Suggestions or Errors? http://dev.bukkit.org/bukkit-plugins/custombroadcast/
# You can use ColorCodes! &a, &b, &c, &d, &e, &f, &0, &1, &2, &3, &4, &5, &6, &7, &8, &9, &l, &n, &m, &k, &o

Prefix: '&8[&3&lDonate&8]&7'
