name: MiniGames
author: O_o_Fadi_o_O
version: 1
description: MiniGames by O_o_Fadi_o_O
main: me.O_o_Fadi_o_O.MiniGames.Start
commands:
  mg:
    description: MiniGames Command!
  mgbuykit:
    description: Buy a Kit!
  hub:
    description: Go to the Hub!
  help:
    description: Help Command!
  servers:
    description: Server Selector!
  vippoints:
    description: VIP Points
  omt:
    description: OMT
  perks:
    description: Cosmetic Perks
depend: [LibsDisguises]
depend: [ProtocolLib]