name: SkyBlock
author: O_o_Fadi_o_O
version: 1
load: STARTUP
description: SkyBlock by O_o_Fadi_o_O
main: me.O_o_Fadi_o_O.SkyBlock.Start
commands:
  island:
    description: Island Command!
  is:
    description: Island Command!
  servers:
    description: Server Selector!
  vippoints:
    description: VIP Points
  omt:
    description: OMT
  perks:
    description: Cosmetic Perks
  votes:
    description: Votes
  vote:
    description: Vote
depend: [Multiverse-Core]
depend: [LibsDisguises]
depend: [Votifier]