Book:
  DisplayName: '&c&lRules'
  Author: '&6SkyGames'
  Slot: 1
  Pages:
    '1':
    - ''
    - '&c&lRules [Page 1]'
    - ''
    - '&01.'
    - '&02.'
    '2':
    - ''
    - '&c&lRules [Page 2]'
    - ''
    - '&03.'
    - '&04.'