name: Hub
author: O_o_Fadi_o_O
version: 1
description: Hub by O_o_Fadi_o_O
main: me.O_o_Fadi_o_O.Hub.Hub
commands:
  servers:
    description: Server Selector!
  vippoints:
    description: VIP Points
  omt:
    description: OMT
  perks:
    description: Cosmetic Perks
  votes:
    description: Votes
  vote:
    description: Vote
  giveMonthlyVIPPoints:
    description: add Monthly VIP Points
  resetMonthlyVIPPoints:
    description: reset Monthly VIP Points
  opmode:
    description: OP Mode
  topvoters:
    description: TopVoters
  eat:
    description: Feed Command.
  feed:
    description: Feed Command.
  fly:
    description: Fly Command.
  gm:
    description: Gamemode Command.
  gamemode:
    description: Gamemode Command.
  gms:
    description: Gamemode Command.
  gmc:
    description: Gamemode Command.
  gma:
    description: Gamemode Command.
  gmspec:
    description: Gamemode Command.
  skull:
    description: Skull Command.
  give:
    description: Give Command.
  teleport:
    description: Teleport Command.
  tp:
    description: Teleport Command.
  setvip:
    description: SetVIP Command.
  setstaff:
    description: SetStaff Command.
  disguise:
    description: Disguise Command.
  dis:
    description: Disguise Command.
  d:
    description: Disguise Command.
  undisguise:
    description: Undisguise Command.
  setlastdonator:
    description: Last Donator Command.
  nick:
    description: Nickname Command.
  afk:
    description: AFK Command.
  ban:
    description: Ban Command.
  unban:
    description: Unban Command.
  kick:
    description: Kick Command.
  kickall:
    description: Kickall Command.
  builder:
    description: Builder Command.    
depend: [Vault]