# Default Config
# CustomBroadcast Plugin Made by O_o_Fadi_o_O
# Got any Suggestions or Errors? http://dev.bukkit.org/bukkit-plugins/custombroadcast/
# You can use ColorCodes! &a, &b, &c, &d, &e, &f, &0, &1, &2, &3, &4, &5, &6, &7, &8, &9, &l, &n, &m, &k, &o

Prefix: '&8[&6&lC&5&lu&3&ls&7&lt&9&lo&2&lm&1&lB&a&lr&4&lo&b&la&f&ld&d&lc&3&la&0&ls&9&lt&8]&7'