name: CustomBroadcast
author: O_o_Fadi_o_O
version: 1.1.2
description: CustomBroadcast by O_o_Fadi_o_O
main: me.O_o_Fadi_o_O.CustomBroadcast.Start
commands:
   custombroadcast:
     description: Show CustomBroadcast Help
   cbroadcast:
     description: /custombroadcast Alias
   cb:
     description: /custombroadcast Alias