name: YoutubeEpisode1
author: O_o_Fadi_o_O
version: 1.0
description: YoutubeEpisode1 by O_o_Fadi_o_O
main: me.O_o_Fadi_o_O.YoutubeEpisode1.Start
commands:
  message:
    description: Eerste Message!
  message2:
    description: Tweede Message!