# DO NOT TOUCH THE SPAWN AMOUNT
EnableGame: false
SpawnsAmount: 0
LobbyMinutes: 2
LobbySeconds: 30
ArenaWorld: world
Lobby:
  x: 0
  y: 0
  z: 0
  world: world
Spectate:
  x: 0
  y: 0
  z: 0
players:
  O_o_Fadi_o_O:
    Points: 0
    Kills: 0
    Deaths: 0
    Lost: 0
    Won: 0
    Left: 0
spawns: