Log:
  UseLog: true
  ReadPrivateMessages: true
  ReadSpies: false
  ReadToggles: false
  ReadMutes: false
  ReadReloads: false
  ReadReloadData: false
  ReadBannedWords: false
  ReadSpam: false
  ReadAdvertising: false
  ReadGlobal: false
  ReadChannels: false
  ReadMuteAll: false
  ReadIgnores: false
  ReadReports: true
  ReadHelpOps: true
  
AntiSpam:
  UseAntiSpam: true
  
  CancelDuplicate: true
  DuplicateSensitivity: 2
  
  CancelTooFastUsage: true
  TooFastTimeCheck: 5
  TooFastMaxUsage: 3
  
  UseCooldown: false
  MessageCooldown: 2
  GlobalCooldown: 2
  
  CancelCaps: true
  MaxCapsInMessage: 10
  
AntiAdvertise:
  UseAntiAdvertise: true
  CancelIPs: true
  CancelDomainNames: true
  
  Kick: true
  
Commands:
  Message:
  - /msg
  - /m
  - /t
  - /tell
  - /w
  - /whisper
  Reply:
  - /r
  - /reply
  Reload:
  - /msgreload
  Spy:
  - /msgspy
  Toggle:
  - /msgtoggle
  Mute:
  - /msgmute
  Global:
  - /msgglobal
  MuteAll:
  - /msgmuteall
  Ignore:
  - /ignore
  Report:
  - /report
  HelpOp:
  - /helpop
  
ServerNames:
  hub: '&b&lHub'
  sg-1: '&6&lSG-1'
  
GlobalChat:
  PermissionRequiredForGlobalMessage: false
  GlobalMessage: '&7[&3&lGlobal&7] &7[%server-sender%&7] &6%sender%&7: &6%msg%'

  UseAutoGlobalChat: false
  Groups:
    '1':
      Servers: 'sg-1|sg-2|sg-3'
      Message: '&7[%server-sender%&7] &6%sender%&7: &6%msg%'
    '2':
      Servers: 'uhc-1|uhc-2|uhc-3'
      Message: '&7[%server-sender%&7] &6%sender%&7: &6%msg%'
  Channels:
    Admins:
      Permission: 'BungeeMSG.channels.admins'
      Message: '&7[&c&lAdmin&7] &7[%server-sender%&7] &6%sender%&7: &6%msg%'
      StartingSymbol: 
      - '/admin '
      ToggleSymbol:
      - '/adminchat '
      - '/ac '
      ToggleEnabled: '&7[&c&lAdmin&7] &aEnabled&7 your &cAdmin Chat&7.'
      ToggleDisabled: '&7[&c&lAdmin&7] &cDisabled&7 your &cAdmin Chat&7.'
    Staff:
      Permission: 'BungeeMSG.channels.staff'
      Message: '&7[&b&lStaff&7] &7[%server-sender%&7] &6%sender%&7: &6%msg%'
      StartingSymbol: 
      - '@'
      ToggleSymbol:
      - '#'
      ToggleEnabled: '&7[&b&lStaff&7] &aEnabled&7 your &bStaff Chat&7.'
      ToggleDisabled: '&7[&b&lStaff&7] &cDisabled&7 your &bStaff Chat&7.'
  Broadcast:
    Broadcast:
      Permission: 'BungeeMSG.broadcast.broadcast'
      NoPermission: '&7You do not have access to this command!'
      WrongUsage: '&7Use &6%cmd% <msg>&7.'
      Messages:
      - '&f'
      - ' &c&lBroadcast &7(&c%sender%&7)'
      - '  &6%msg%'
      Commands:
      - /broadcast
      - /bc
  AutoAnnounce:
    '1':
      Servers: [ALL]
      Delay: 60
      Messages:
        '1':
          - '&f'
          - ' &6&lBungee&7&lMSG &7- &dAutoAnnouncer'
          - '&f'
        '2':
          - '&f'
          - ' &6&lBungee&7&lMSG &7- &dNew v1.7.1 feature.'
          - '&f'
    '2':
      Servers: 'hub|sg-1'
      Delay: 120
      Messages:
        '1':
          - '&f'
          - ' &6&lBungee&7&lMSG &7- &bWill only be shown in the Hub and SG-1 Server!'
          - '&f'
        '2':
          - '&f'
          - ' &6&lBungee&7&lMSG &7- &bHello %receiver%!'
          - '&f'
      
PlayerNameSuggest:
  HoverMessage: '&7Click to message &6%receiver%&7.'
  SuggestedCommand: '/msg %receiver%'

Receiver: '&7[%server-sender%&7] &6%suggest-player% &7> &7[%server-receiver%&7] &6%receiver%&7: &6%msg%'
Sender: '&7[%server-sender%&7] &6%sender% &7> &7[%server-receiver%&7] &6%suggest-player%&7: &6%msg%'

EnableInfo: true
Info: '&7Use &6/r <msg>&7 to reply.'

PlayerNotOnline: '&6%receiver% &7isn''t Online!'
NoReceiver: '&7You have nobody to reply to.'
ToThemselves: '&7You cannot send a message to yourself!'

WrongUsageMSG: '&7Use &6%cmd% <player> <msg>&7.'
WrongUsageReply: '&7Use &6%cmd% <msg>&7.'
WrongUsageToggle: '&7Use &6%cmd% &7or &6%cmd% <player>&7.'
WrongUsageMute: '&7Use &6%cmd% <player>&7.'
WrongUsageGlobal: '&7Use &6%cmd% <msg>&7.'
WrongUsageMuteAll: '&7Use &6%cmd% &7or &6%cmd% <server>&7.'
WrongUsageIgnore: '&7Use &6%cmd% <player>&7.'
WrongUsageReport: '&7Use &6%cmd% <player> <reason>&7.'
WrongUsageHelpOp: '&7Use &6%cmd% <reason>&7.'

NoReloadPermission: '&7You do not have access to this command!'
NoSpyPermission: '&7You do not have access to this command!'
NoTogglePermission: '&7You do not have access to this command!'
NoToggleOtherPermission: '&7You do not have access to this command!'
NoMutePermission: '&7You do not have access to this command!'
NoGlobalPermission: '&7You do not have access to this command!'
NoMuteAllPermission: '&7You do not have access to this command!'
NoIgnorePermission: '&7You do not have access to this command!'
NoMessagePermission: '&7You do not have access to this command!'
NoReplyPermission: '&7You do not have access to this command!'

SpyPrefix: '&eSpy &8| '
SpyMessage: '&7[%server-sender%&7] &6%sender% &7> &7[%server-receiver%&7] &6%receiver%&7: &6%msg%'
SpyEnable: '&aEnabled &eSpy Mode&7!'
SpyDisable: '&cDisabled &eSpy Mode&7!'

TellSenderIfDisabled: false
DisabledMessage: '&6%receiver% &cDisabled&7 Private Messages!'

ToggleEnable: '&aEnabled &7Private Messages!'
ToggleDisable: '&cDisabled &7Private Messages!'
ToggleEnableToSender: '&aEnabled &6%toggled%''s &7Private Messages!'
ToggleEnableToPlayer: '&6%sender% &aEnabled &7your Private Messages!'
ToggleDisableToSender: '&cDisabled &6%toggled%''s &7Private Messages!'
ToggleDisableToPlayer: '&6%sender% &cDisabled &7your Private Messages!'
ToggleOnSend: '&7Your Private Messages have been &cDisabled&7!'

MuteToSender: '&7You muted &6%muted%&7!'
UnmuteToSender: '&7You unmuted &6%muted%&7!'
MuteToPlayer: '&7You have been muted by &6%sender%&7!'
UnmuteToPlayer: '&7You have been unmuted by &6%sender%&7!'
MutedMessage: '&7You cannot use private messages. You have been muted!'

SpamDuplicate: '&7Spamming is not allowed here!'
SpamTooFast: '&7You''re sending messages too fast!'
SpamCooldown: '&7You have to wait %left% more %second-grammer% before sending a Private Message again!'

SecondGrammerVariableOne: 'second'
SecondGrammerVariableMultiple: 'seconds'

AdvertiseKickMessage: '&6&lKicked! &7Sending &6%type%&7 through PMs isn''t allowed!'
AdvertiseMessage: '&7You''re not allowed to send &6%type%&7 through Private Messages!'
  
TypeVariableIPs: 'IPs'
TypeVariableDomainNames: 'websites'

MuteAllToSender: '&6Muted&7 all Players!'
MuteAllToPlayer: '&7You have been muted by &6%sender%&7!'
UnmuteAllToSender: '&6Unmuted&7 all Players!'
UnmuteAllToPlayer: '&7You have been unmuted by &6%sender%&7!'
MuteServerToSender: '&6Muted&7 all Players in %server-name%&7!'
UnmuteServerToSender: '&6Unmuted&7 all Players in %server-name%!&&'

UseIgnorePermission: true
Ignore: '&7You''re now ignoring &6%ignored%&7!'
NoIgnore: '&7You''re no longer ignoring &6%ignored%&7.'
IsIgnored: '&7You ignored &6%receiver%&7!'

TellSenderIfIgnored: true
IgnoredMessage: '&6%receiver%&7 ignored you.'

UseMessagePermission: false
UseReplyPermission: false

ReportCooldown: 600
ReportOnCooldown: '&7You may only report a player once every &610 minutes&7!'
ReportedMessage: '&7Succesfully reported &6%reported%&7! (&6%reason%&7)'
ReportedStaffMessage: '&7[&cReport&7] [%server-sender%&7] &6%sender% &7-> [%server-reported%&7] &c%reported%&7. (&6%reason%&7)'

HelpOpCooldown: 300
HelpOpOnCooldown: '&7You may only ask for help every &65 minutes&7!'
HelpOpMessage: '&7Succesfully asked for help! (&6%reason%&7)'
HelpOpStaffMessage: '&7[&dHelpOp&7] [%server-sender%&7] &6%sender%&7: &d%reason%'