name: DonateBroadcast
author: O_o_Fadi_o_O
version: 1.1.2
description: DonateBroadcast by O_o_Fadi_o_O
main: me.O_o_Fadi_o_O.DonateBroadcast.Start
commands:
   custombroadcast:
     description: Show CustomBroadcast Help
   cbroadcast:
     description: /custombroadcast Alias
   cb:
     description: /custombroadcast Alias