Settings:
  BungeeCord:
    BungeeCord: false
    IsHubServer: false
    HubServer: 'hub'
    ThisArenaIDForHub: 1
    ThisBungeeServerName: 'spleef-1'
    ServersIfHubServer:
      '1': 'spleef-1'
      '2': 'spleef-2'
      '3': 'spleef-3'

    MOTD:
      UseMOTD: true
      UpdateMaxPlayers: true
      
  MySQLDatabase:
    UseMySQL: false
    ImportFromPlayerData: false
    hostname: ''
    port: ''
    databasename: ''
    username: ''
    password: ''
    
  VIPRanks:
    VIP:
      Permission: 'SpigotSpleef.multiplier.vip'
      Multiplier: 2.0
      MultiplierName: ' &6&lx2 VIP'
    MVP:
      Permission: 'SpigotSpleef.multiplier.mvp'
      Multiplier: 3.0
      MultiplierName: ' &6&lx3 MVP'
   
  MaxPlayers: 16
  MinPlayers: 3

  NewPlayerUnlockedKits: '1 | 2'
  NewPlayerTokens: 0

  StartingMessage: '0:45 | 0:30 | 0:20 | 0:10 | 0:9 | 0:8 | 0:7 | 0:6 | 0:5 | 0:4 | 0:3 | 0:2 | 0:1'
  EndingMessage: '5:0 | 3:0 | 1:0 | 0:30 | 0:10 | 0:9 | 0:8 | 0:7 | 0:6 | 0:5 | 0:4 | 0:3 | 0:2 | 0:1'
  
  WaitTimeMinutes: 0
  WaitTimeSeconds: 30
  
  WarmupTimeSeconds: 10
  
  MaxGameTimeMinutes: 10
  MaxGameTimeSeconds: 0
   
  EndingTimeSeconds: 10
  
  CanPunch: true
  
  UsePerArenaChat: true
  
  DieWhenYIs: 0
  
  TokensPerKill: 3
  TokensFirstPlace: 10
  TokensSecondPlace: 5
  TokensThirdPlace: 3
  
  TokenMotivier:
    UseVault: false
    UseCustomTokens: true
  
  CommandRewards:
    UseCommandRewards: false
    
    FirstPlace:
    - coins add %player% 100
    SecondPlace:
    - coins add %player% 50
    ThirdPlace:
    - coins add %player% 25
    Kill:
    - coins add %player% 5
  
  WhitelistedCommands:
  - /msg
  - /r
  - /me
  - /reload

  Scoreboards:
    Waiting:
      Title: '&6&lSpigot&7&lSpleef' 
      Rows:
      - '<score>14</score> <row></row>'
      - '<score>13</score> <row>&f&lWaiting%animated-dots%</row>'
      - '<score>12</score> <row> </row>'
      - '<score>11</score> <row>&6&lPlayers</row>'
      - '<score>10</score> <row> &7%players%/%max-players%</row>'
      - '<score>9</score> <row>  </row>'
      - '<score>8</score> <row>&e&lKit</row>'
      - '<score>7</score> <row> &7%kit-name%</row>'
      - '<score>6</score> <row>   </row>'
      - '<score>5</score> <row>&f&lSpleef Tokens</row>'
      - '<score>4</score> <row> &7%tokens%</row>'
      - '<score>3</score> <row>    </row>'
      - '<score>2</score> <row>&a&lMap</row>'
      - '<score>1</score> <row> &7%map-name%</row>'
      - '<score>0</score> <row>     </row>'
    EnoughPlayers:
      Title: '&6&lSpigot&7&lSpleef' 
      Rows:
      - '<score>14</score> <row></row>'
      - '<score>13</score> <row>&f&lStarting in &6&l%seconds%</row>'
      - '<score>12</score> <row> </row>'
      - '<score>11</score> <row>&6&lPlayers</row>'
      - '<score>10</score> <row> &7%players%/%max-players%</row>'
      - '<score>9</score> <row>  </row>'
      - '<score>8</score> <row>&e&lKit</row>'
      - '<score>7</score> <row> &7%kit-name%</row>'
      - '<score>6</score> <row>   </row>'
      - '<score>5</score> <row>&f&lSpleef Tokens</row>'
      - '<score>4</score> <row> &7%tokens%</row>'
      - '<score>3</score> <row>    </row>'
      - '<score>2</score> <row>&a&lMap</row>'
      - '<score>1</score> <row> &7%map-name%</row>'
      - '<score>0</score> <row>     </row>'
    InGame:
      Title: '&6&lSpigot&7&lSpleef' 
      Rows:
      - '<score>6</score> <row></row>'
      - '<score>5</score> <row>&a&lPlayers</row>'
      - '<score>4</score> <row> &7%players%</row>'
      - '<score>3</score> <row> </row>'
      - '<score>2</score> <row>&e&lSpectators</row>'
      - '<score>1</score> <row> &7%spectators%</row>'
      - '<score>0</score> <row>  </row>'
      
  Signs:
    Waiting:
    - '&2&lSpleef-%arena-id%'
    - '&a%players%&0/&a%max-players%'
    - '&2&lJoin'
    - '&aWaiting%animated-dots%'
    EnoughPlayers:
    - '&2&lSpleef-%arena-id%'
    - '&a%players%&0/&a%max-players%'
    - '&2&lJoin'
    - '&a%minutes%m %seconds%s'
    Full:
    - '&4&lSpleef-%arena-id%'
    - '&c%players%&0/&c%max-players%'
    - '&4&lFull'
    - '&c%minutes%m %seconds%s'
    InGame:
    - '&6&lSpleef-%arena-id%'
    - '&e%players%&0/&e%max-players%'
    - '&6&lSpectate'
    - '&e%minutes%m %seconds%s'
    Restarting:
    - '&4&m------------'
    - '&c&lSpleef-%arena-id%'
    - '&0&lRESTARTING'
    - '&4&m------------'
    
  MOTD:
    Waiting: '&6&lSpigot&7&lSpleef &7- &c&lArena %arena-id% \n &7Players: &a%players%&7/&a%max-players% &7Status: &aWaiting...'
    EnoughPlayers: '&6&lSpigot&7&lSpleef &7- &c&lArena %arena-id% \n &7Players: &a%players%&7/&a%max-players% &7Status: &aStarting in %seconds%...'
    Full: '&6&lSpigot&7&lSpleef &7- &c&lArena %arena-id% \n &7Players: &c%players%&7/&c%max-players% &7Status: &cFull'
    InGame: '&6&lSpigot&7&lSpleef &7- &c&lArena %arena-id% \n &7Players: &e%players%&7/&e%max-players% &7Status: &eIn Game'
    Restarting: '&6&lSpigot&7&lSpleef &7- &c&lArena %arena-id% \n &4&lRESTARTING'
    
  LobbyInventory:
    '9':
      ItemType: LEAVE_GAME
      Name: '&3&lLeave Game'
      Type: ENDER_PEARL
      Durability: 0
      Amount: 1     
  
  SpectatorInventory:
    '9':
      ItemType: LEAVE_GAME
      Name: '&3&lLeave Game'
      Type: ENDER_PEARL
      Durability: 0
      Amount: 1
  
  NPCInventory:
    ArenaSelector:
      Size: 54
      Name: '&0&lSpigotSpleef'
      Inventory:
        '5':
          ItemType: NORMAL
          Name: '&6&lSpigot&7&lSpleef'
          Lore: []
          Type: IRON_SPADE
          Durability: 0
          Amount: 1
        '20':
          ItemType: ARENA
          ArenaID: 1
        '21':
          ItemType: ARENA
          ArenaID: 2
        '22':
          ItemType: ARENA
          ArenaID: 3
        '23':
          ItemType: ARENA
          ArenaID: 4
        '24':
          ItemType: ARENA
          ArenaID: 5
        '25':
          ItemType: ARENA
          ArenaID: 6
        '26':
          ItemType: ARENA
          ArenaID: 7
        '29':
          ItemType: ARENA
          ArenaID: 8
        '30':
          ItemType: ARENA
          ArenaID: 9
        '31':
          ItemType: ARENA
          ArenaID: 10
        '32':
          ItemType: ARENA
          ArenaID: 11
        '33':
          ItemType: ARENA
          ArenaID: 12
        '34':
          ItemType: ARENA
          ArenaID: 13
        '35':
          ItemType: ARENA
          ArenaID: 14
        '38':
          ItemType: ARENA
          ArenaID: 15
        '39':
          ItemType: ARENA
          ArenaID: 16
        '40':
          ItemType: ARENA
          ArenaID: 17
        '41':
          ItemType: ARENA
          ArenaID: 18
        '42':
          ItemType: ARENA
          ArenaID: 19
        '43':
          ItemType: ARENA
          ArenaID: 20
        '44':
          ItemType: ARENA
          ArenaID: 21
      ItemTypes:
        Waiting:
          Name: '&2&lSpleef-%arena-id%'
          Lore:
          - '&7&lStatus: &2&lJoin'
          - '&7&lPlayers: &a&l%players%&7&l/&a&l%max-players%' 
          Type: STAINED_GLASS
          Durability: 5
          Amount: '%players%'
        EnoughPlayers:
          Name: '&2&lSpleef-%arena-id%'
          Lore:
          - '&7&lStatus: &2&lJoin'
          - '&7&lPlayers: &a&l%players%&7&l/&a&l%max-players%' 
          - '&7&lTime Left: &a&l%minutes%m %seconds%s' 
          Type: STAINED_GLASS
          Durability: 5
          Amount: '%players%'
        Full:
          Name: '&4&lSpleef-%arena-id%'
          Lore:
          - '&7&lStatus: &4&lFull'
          - '&7&lPlayers: &c&l%players%&7&l/&c&l%max-players%' 
          - '&7&lTime Left: &c&l%minutes%m %seconds%s' 
          Type: STAINED_GLASS
          Durability: 14
          Amount: '%players%'
        InGame:
          Name: '&6&lSpleef-%arena-id%'
          Lore:
          - '&7&lStatus: &6&lIn Game'
          - '&7&lPlayers: &e&l%players%&7&l/&e&l%max-players%'
          - '&7&lSpectators: &e&l%spectators%'  
          - '&7&lTime Left: &e&l%minutes%m %seconds%s' 
          Type: STAINED_GLASS
          Durability: 4
          Amount: '%players%'
        Restarting:
          Name: '&6&lSpleef-%arena-id%'
          Lore:
          - '&7&lStatus: &8&lRestarting%animated-dots%'
          Type: STAINED_GLASS
          Durability: 15
          Amount: 1

    BuyKit:
      Size: 27
      Name: '&0&lBuy %kit-name%'
      Inventory:
        '14':
          ItemType: NORMAL
          Name: '&6&l%kit-name%'
          Lore:
          - ''
          - ' &7Price: &6%price% Tokens '
          - ''
          Type: IRON_SPADE
          Durability: 0
          Amount: 1
        '1':
          ItemType: CONFIRM_PURCHASE
          Name: '&a&lConfirm'
          Lore: []
          Type: STAINED_GLASS_PANE
          Durability: 5
          Amount: 1
        '2':
          ItemType: CONFIRM_PURCHASE
          Name: '&a&lConfirm'
          Lore: []
          Type: STAINED_GLASS_PANE
          Durability: 5
          Amount: 1
        '3':
          ItemType: CONFIRM_PURCHASE
          Name: '&a&lConfirm'
          Lore: []
          Type: STAINED_GLASS_PANE
          Durability: 5
          Amount: 1
        '4':
          ItemType: CONFIRM_PURCHASE
          Name: '&a&lConfirm'
          Lore: []
          Type: STAINED_GLASS_PANE
          Durability: 5
          Amount: 1
        '10':
          ItemType: CONFIRM_PURCHASE
          Name: '&a&lConfirm'
          Lore: []
          Type: STAINED_GLASS_PANE
          Durability: 5
          Amount: 1
        '11':
          ItemType: CONFIRM_PURCHASE
          Name: '&a&lConfirm'
          Lore: []
          Type: STAINED_GLASS_PANE
          Durability: 5
          Amount: 1
        '12':
          ItemType: CONFIRM_PURCHASE
          Name: '&a&lConfirm'
          Lore: []
          Type: STAINED_GLASS_PANE
          Durability: 5
          Amount: 1
        '13':
          ItemType: CONFIRM_PURCHASE
          Name: '&a&lConfirm'
          Lore: []
          Type: STAINED_GLASS_PANE
          Durability: 5
          Amount: 1
        '19':
          ItemType: CONFIRM_PURCHASE
          Name: '&a&lConfirm'
          Lore: []
          Type: STAINED_GLASS_PANE
          Durability: 5
          Amount: 1
        '20':
          ItemType: CONFIRM_PURCHASE
          Name: '&a&lConfirm'
          Lore: []
          Type: STAINED_GLASS_PANE
          Durability: 5
          Amount: 1
        '21':
          ItemType: CONFIRM_PURCHASE
          Name: '&a&lConfirm'
          Lore: []
          Type: STAINED_GLASS_PANE
          Durability: 5
          Amount: 1
        '22':
          ItemType: CONFIRM_PURCHASE
          Name: '&a&lConfirm'
          Lore: []
          Type: STAINED_GLASS_PANE
          Durability: 5
          Amount: 1
        '6':
          ItemType: CANCEL_PURCHASE
          Name: '&c&lCancel'
          Lore: []
          Type: STAINED_GLASS_PANE
          Durability: 14
          Amount: 1
        '7':
          ItemType: CANCEL_PURCHASE
          Name: '&c&lCancel'
          Lore: []
          Type: STAINED_GLASS_PANE
          Durability: 14
          Amount: 1
        '8':
          ItemType: CANCEL_PURCHASE
          Name: '&c&lCancel'
          Lore: []
          Type: STAINED_GLASS_PANE
          Durability: 14
          Amount: 1
        '9':
          ItemType: CANCEL_PURCHASE
          Name: '&c&lCancel'
          Lore: []
          Type: STAINED_GLASS_PANE
          Durability: 14
          Amount: 1
        '15':
          ItemType: CANCEL_PURCHASE
          Name: '&c&lCancel'
          Lore: []
          Type: STAINED_GLASS_PANE
          Durability: 14
          Amount: 1
        '16':
          ItemType: CANCEL_PURCHASE
          Name: '&c&lCancel'
          Lore: []
          Type: STAINED_GLASS_PANE
          Durability: 14
          Amount: 1
        '17':
          ItemType: CANCEL_PURCHASE
          Name: '&c&lCancel'
          Lore: []
          Type: STAINED_GLASS_PANE
          Durability: 14
          Amount: 1
        '18':
          ItemType: CANCEL_PURCHASE
          Name: '&c&lCancel'
          Lore: []
          Type: STAINED_GLASS_PANE
          Durability: 14
          Amount: 1
        '24':
          ItemType: CANCEL_PURCHASE
          Name: '&c&lCancel'
          Lore: []
          Type: STAINED_GLASS_PANE
          Durability: 14
          Amount: 1
        '25':
          ItemType: CANCEL_PURCHASE
          Name: '&c&lCancel'
          Lore: []
          Type: STAINED_GLASS_PANE
          Durability: 14
          Amount: 1
        '26':
          ItemType: CANCEL_PURCHASE
          Name: '&c&lCancel'
          Lore: []
          Type: STAINED_GLASS_PANE
          Durability: 14
          Amount: 1
        '27':
          ItemType: CANCEL_PURCHASE
          Name: '&c&lCancel'
          Lore: []
          Type: STAINED_GLASS_PANE
          Durability: 14
          Amount: 1
      
Kits:
  '1':
    KitName: Spleef Recruit
    Price: 0
    Inventory:
      '1':
        Name: '&7&lAxe %animated-right-click%'
        Type: IRON_AXE
        Durability: 0
        Amount: 1
        Ability: JUMP
      '9':
        Name: '&7&lTarget: &6&l%target%         &7&lDistance: &6&l%distance%'
        Type: COMPASS
        Durability: 0
        Amount: 1
        Ability: NEAREST_PLAYER
  '2':
    KitName: Spleef Bowman
    Price: 1000
    Inventory:
      '1':
        Name: '&7&lBow'
        Type: BOW
        Durability: 0
        Amount: 1
        Ability: RANGE_MEDIUM
      '2':
        Name: '&7&lArrow'
        Type: ARROW
        Durability: 0
        Amount: 1
        Ability: PLUS_ONE_1
      '9':
        Name: '&7&lTarget: &6&l%target%         &7&lDistance: &6&l%distance%'
        Type: COMPASS
        Durability: 0
        Amount: 1
        Ability: NEAREST_PLAYER 
  '3':
    KitName: Spleef Bomber
    Price: 2000
    Inventory:
      '1':
        Name: '&7&lTNT'
        Type: TNT
        Durability: 0
        Amount: 1
        Ability: INSTANT_TNT|PLUS_ONE_2
      '9':
        Name: '&7&lTarget: &6&l%target%         &7&lDistance: &6&l%distance%'
        Type: COMPASS
        Durability: 0
        Amount: 1
        Ability: NEAREST_PLAYER  
  '4':
    KitName: Spleef Enderman
    Price: 3000
    Inventory:
      '1':
        Name: '&7&lBow'
        Type: BOW
        Durability: 0
        Amount: 1
        Ability: TELEPORT_ARROWS
      '2':
        Name: '&7&lArrow'
        Type: ARROW
        Durability: 0
        Amount: 1
        Ability: PLUS_ONE_3
      '5':
        Name: '&3&lEnder Pearl'
        Type: ENDER_PEARL
        Durability: 0
        Amount: 1
        Ability: PLUS_ONE_4
      '9':
        Name: '&7&lTarget: &6&l%target%         &7&lDistance: &6&l%distance%'
        Type: COMPASS
        Durability: 0
        Amount: 1
        Ability: NEAREST_PLAYER
  '5':
    KitName: Splegg Chicken
    Price: 4000
    Inventory:
      '1':
        Name: '&7&lShovel %animated-right-click%'
        Type: IRON_SPADE
        Durability: 0
        Amount: 1
        Ability: THROW_EGG
      '9':
        Name: '&7&lTarget: &6&l%target%         &7&lDistance: &6&l%distance%'
        Type: COMPASS
        Durability: 0
        Amount: 1
        Ability: NEAREST_PLAYER
  '6':
    KitName: Spleef Ocelot
    Price: 2500
    Inventory:
      '1':
        Name: '&7&lRaw Fish %animated-right-click%'
        Type: RAW_FISH
        Durability: 0
        Amount: 1
        Ability: SPEED_BOOST
      '9':
        Name: '&7&lTarget: &6&l%target%         &7&lDistance: &6&l%distance%'
        Type: COMPASS
        Durability: 0
        Amount: 1
        Ability: NEAREST_PLAYER
  '7':
    KitName: Spleef Runner
    Price: 4000
    Inventory:
      '9':
        Name: '&7&lTarget: &6&l%target%         &7&lDistance: &6&l%distance%'
        Type: COMPASS
        Durability: 0
        Amount: 1
        Ability: NEAREST_PLAYER
      '37':
        Name: '&7&lBoots'
        Type: LEATHER_BOOTS
        Durability: 0
        Amount: 1
        Ability: RUNNER
  '8':
    KitName: Spleef Builder
    Price: 5000
    Inventory:
      '1':
        Name: '&7&lStone'
        Type: STONE
        Durability: 0
        Amount: 1
        Ability: PLACE_ABLE|PLUS_ONE_5
      '2':
        Name: '&7&lGrass'
        Type: GRASS
        Durability: 0
        Amount: 1
        Ability: PLACE_ABLE|PLUS_ONE_5
      '3':
        Name: '&7&lDIRT'
        Type: DIRT
        Durability: 0
        Amount: 1
        Ability: PLACE_ABLE|PLUS_ONE_5
      '9':
        Name: '&7&lTarget: &6&l%target%         &7&lDistance: &6&l%distance%'
        Type: COMPASS
        Durability: 0
        Amount: 1
        Ability: NEAREST_PLAYER

AbilityMotiviers:
  JUMP:
    Cooldown: 3
    Power: 4
    Sound: FIREWORK_BLAST
  PLUS_ONE_1:
    Cooldown: 10
    Sound: ITEM_PICKUP
    MaxAmount: 2
  PLUS_ONE_2:
    Cooldown: 5
    Sound: ITEM_PICKUP
    MaxAmount: 3
  PLUS_ONE_3:
    Cooldown: 15
    Sound: ITEM_PICKUP
    MaxAmount: 3
  PLUS_ONE_4:
    Cooldown: 20
    Sound: ITEM_PICKUP
    MaxAmount: 2
  PLUS_ONE_5:
    Cooldown: 12
    Sound: ITEM_PICKUP
    MaxAmount: 5
  TELEPORT_ARROWS:
    Sound: ENDERMAN_TELEPORT
  THROW_EGG:
    Cooldown: 0
  SPEED_BOOST:
    Cooldown: 10
    Power: 2
    Duration: 4
    Sound: DRINK
  RUNNER:
    Duration: 1

Blocks:
  '1:0': '4:0'
  '2:0': '3:0'
  '17:0': '162:1'
  '98:0': '98:2'