# Default Config
# ChatColors Plugin Made by O_o_Fadi_o_O
# Got any Suggestions or Errors? http://dev.bukkit.org/bukkit-plugins/onkill/
# You can use ColorCodes! &a, &b, &c, &d, &e, &f, &0, &1, &2, &3, &4, &5, &6, &7, &8, &9, &l, &n, &m, &k, &o
players:
  O_o_Fadi_o_O: '§4'

